# Generated by Django 5.2.17 on 2026-08-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0021_remove_oncallschedule_channel_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncallschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='oncallschedulecalendar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='oncallscheduleical',
            options={},
        ),
        migrations.AlterModelOptions(
            name='oncallscheduleweb',
            options={},
        ),
    ]
