# Generated by Django 5.2.17 on 2026-08-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0075_alter_alertgrouplogrecord_action_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertgrouplogrecord',
            name='action_source',
            field=models.SmallIntegerField(default=None, null=True, verbose_name=[(0, 'Slack'), (1, 'Web'), (2, 'Phone'), (3, 'Telegram'), (4, 'API'), (5, 'Backsync'), (6, 'Mattermost'), (7, 'Discord')]),
        ),
    ]
