# Generated by Django 5.2.17 on 2026-08-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0076_alter_alertgrouplogrecord_action_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionnote',
            name='source',
            field=models.IntegerField(choices=[(0, 'Slack'), (1, 'Web'), (2, 'Mobile App'), (3, 'Discord')], default=None, null=True),
        ),
    ]
