# Generated by Django 5.2.17 on 2026-08-13 23:46

import apps.discord.models.channel
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0076_alter_alertgrouplogrecord_action_source'),
        ('user_management', '0029_remove_organization_general_log_channel_id_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_primary_key', models.CharField(default=apps.discord.models.channel.generate_public_primary_key_for_discord_channel, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('guild_id', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(default=None, max_length=100)),
                ('is_default_channel', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_channels', to='user_management.organization')),
            ],
            options={
                'unique_together': {('organization', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('message_type', models.IntegerField(choices=[(0, 'Alert group message'), (1, 'Log message')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_messages', to='alerts.alertgroup')),
            ],
            options={
                'indexes': [models.Index(fields=['channel_id', 'message_id'], name='discord_dis_channel_5a078d_idx')],
                'constraints': [models.UniqueConstraint(fields=('alert_group', 'message_type', 'channel_id'), name='unique_discord_alert_group_message_type_channel_id')],
            },
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_user_identity', to='user_management.user')),
            ],
            options={
                'indexes': [models.Index(fields=['discord_user_id'], name='discord_dis_discord_fa1f31_idx')],
            },
        ),
    ]
