# Generated by Django 5.2.17 on 2026-08-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannel',
            name='available_tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='channel_type',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='discordmessage',
            name='thread_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
